std_msgs/Float32MultiArray weights # provides the weights of the neural network policy.
---
# provides the transition data collected during the rollout.
std_msgs/Float32MultiArray states
std_msgs/Float32MultiArray actions
