---
float32 battery	      # indicates the battery voltage
uint16 number_weights  # indicates the number of weigts of the policy. This is useful to automatically initialize the training algorithms
string error_message  # for error messages
